"""empty message

Revision ID: 0916336df627
Revises: 4e422cadb770
Create Date: 2022-03-01 15:19:48.867348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0916336df627'
down_revision = '4e422cadb770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('created_user', sa.Integer(), nullable=True, comment='创建数据的用户ID'),
    sa.Column('updated_user', sa.Integer(), nullable=True, comment='修改数据的用户ID'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='字段名'),
    sa.Column('value', sa.Text(), nullable=True, comment='字段值'),
    sa.Column('type', sa.String(length=128), nullable=True, comment='配置类型'),
    sa.Column('desc', sa.Text(), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config')),
    sa.UniqueConstraint('name', name=op.f('uq_config_name'))
    )
    op.create_table('config_type',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('created_user', sa.Integer(), nullable=True, comment='创建数据的用户ID'),
    sa.Column('updated_user', sa.Integer(), nullable=True, comment='修改数据的用户ID'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='字段名'),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_type')),
    sa.UniqueConstraint('name', name=op.f('uq_config_type_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_type')
    op.drop_table('config')
    # ### end Alembic commands ###
