"""initial migration

Revision ID: 4e422cadb770
Revises: 
Create Date: 2022-01-12 12:46:15.335328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e422cadb770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('created_user', sa.Integer(), nullable=True, comment='创建数据的用户ID'),
    sa.Column('updated_user', sa.Integer(), nullable=True, comment='修改数据的用户ID'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='权限名称'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('name', name=op.f('uq_permission_name'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('created_user', sa.Integer(), nullable=True, comment='创建数据的用户ID'),
    sa.Column('updated_user', sa.Integer(), nullable=True, comment='修改数据的用户ID'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='角色名称'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_roles_permissions_permission_id_permission')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_roles_permissions_role_id_role'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('created_user', sa.Integer(), nullable=True, comment='创建数据的用户ID'),
    sa.Column('updated_user', sa.Integer(), nullable=True, comment='修改数据的用户ID'),
    sa.Column('account', sa.String(length=50), nullable=True, comment='账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('name', sa.String(length=12), nullable=True, comment='姓名'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态，1为启用，2为冻结'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='所属的角色id'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_users_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles_permissions')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
