"""initial migration

Revision ID: 71f8d4bc70c0
Revises: 80d493d9abe0
Create Date: 2021-12-20 17:16:23.115868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f8d4bc70c0'
down_revision = '80d493d9abe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'PasteFile', ['filemd5'])
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'login_count')
    op.drop_constraint(None, 'PasteFile', type_='unique')
    # ### end Alembic commands ###
